name: Robô Canindé

on:
  schedule:
    # Roda a cada 15 minutos
    - cron: '*/15 * * * *'
  workflow_dispatch: # Permite rodar manualmente para testar

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar o código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar bibliotecas
        run: |
          pip install -r requirements.txt

      - name: Criar arquivo de credenciais
        # Cria o arquivo json temporário usando o segredo guardado no GitHub
        run: echo '${{ secrets.CREDENTIALS_JSON }}' > credentials.json

      - name: Rodar o script
        # Aqui injetamos as variáveis de ambiente que o script novo exige
        env:
          EMAIL_REMETENTE: ${{ secrets.EMAIL_REMETENTE }}
          SENHA_EMAIL: ${{ secrets.SENHA_EMAIL }}
          EMAIL_DESTINATARIO: ${{ secrets.EMAIL_DESTINATARIO }}
        # IMPORTANTE: Atualizei o nome para o novo nome sem acentos
        run: python automacao_emenda.py
